---
title: "ANOVA F-Test Power Calculator for Two or more Means"
output: 
  flexdashboard::flex_dashboard:
    theme: cerulean
    orientation: columns
    social: menu
    source_code: embed
runtime: shiny
---



```{r global, include=FALSE}
library(shiny)
library(ggplot2)
##### Function Defined:
powerg <- function(muvec = c(5, 8, 2, 6), nvec = c(25, 30, 20, 24), sig = 6, alpha = 0.05){
n_vec <- unlist(strsplit(nvec, ","))
mu_vec <- unlist(strsplit(muvec, ","))
mu_vec <- as.numeric(mu_vec)
g <- length(mu_vec)
n_vec <- as.numeric(n_vec)
N <- sum(n_vec) # Total sample size
mu <- sum(n_vec*mu_vec)/N # grand mean
lambda <- sum(n_vec*((mu_vec - mu)^2))/sig^2
LAMBDA <- round(lambda, 4)
ll <- 0.0000001       # Alan changed
ul <- qf(.98, g-1, N-g, lambda) # Alan changed

# Alan added if else statement
if(g <= 3){
p <- ggplot(data = data.frame(x = c(ll+ 0.1, ul)), aes(x = x)) + ylim(0, 1)
} else {
p <- ggplot(data = data.frame(x = c(ll, ul)), aes(x = x))   
}
# Alan changed names to df vs dt
df_fun1 <- function(x){
      y <- df(x, g - 1, N - g)
      y[x < qf(1 - alpha, g - 1, N - g)] <- NA
      return(y)
    }
    
df_fun2 <- function(x){
      y <- df(x, g - 1, N - g, lambda)
      y[x < qf(1 - alpha, g - 1, N - g)] <- NA
      return(y)
    } 
    
df_fun3 <- function(x){
      y <- df(x, g - 1, N - g, lambda)
      y[x > qf(1 - alpha, g - 1, N - g)] <- NA
      return(y)
    }
    
POWER <- round(pf(qf(1-alpha,  g - 1, N - g),  g - 1, N - g, ncp = lambda, lower.tail = FALSE), 4)
BETA <- 1- POWER

# Alan added linewidth = 1.5, theme_classic(), and Lambda comment  
p + stat_function(fun = df_fun1, geom = "area", n = 1500, fill = "red", alpha = 0.95) +
    stat_function(fun = df_fun2, geom = "area", n = 1500, fill = "blue", alpha = 0.4) +
    stat_function(fun = df_fun3, geom = "area", n = 1500, fill = "green", alpha = 0.5) +
    stat_function(fun = df, args = list(g - 1, N - g), n = 1500, color = "red", linewidth = 1.5) +
    stat_function(fun = df, args = list(g - 1, N - g, lambda), n = 1500, color = "blue", linewidth = 1.5) +
    geom_hline(yintercept = 0, linewidth = 1.5) +
    theme_classic(base_size = 16) +
    labs(x = "", y = "", 
       title = paste0("Power ","(",POWER,") is the sum of all blue and purple shaded areas"),
       subtitle = "Null distribution is the red density - True distribution is the blue density",
       caption = paste0("Beta ","(",BETA,") is the green shaded area.", " Lambda ", "(",LAMBDA,") is the statistical difference.") ) +
    theme(plot.title = element_text(hjust = 0.5)) + 
    theme(plot.subtitle = element_text(hjust = 0.5)) + 
    theme(plot.caption = element_text(hjust = 0.5)) +
    annotate("text", qf(.5, g - 1, N - g) + 0.5, df(qf(.5, g - 1, N - g), g - 1, N - g) + 0.05, label = expression(F["a - 1, N - a"]), color = "red", parse = TRUE) + 
    annotate("text", qf(.5, g - 1, N - g, lambda) + 0.5, df(qf(.5, g - 1, N - g, lambda), g - 1, N - g, lambda) + 0.05, label = expression(F["a - 1, N - a, lambda"]), color = "blue", parse = TRUE) 
}
```


Column {.sidebar}
-----------------

Null and alternative hypotheses:

$H_0: \mu_1 = \mu_2 = \cdots = \mu_a$
$H_A: \mu_i \neq \mu_j$ for some ($i, j$)

---

```{r}

textInput(inputId = 'vec1', 'Enter \\( \\mu_1 \\), \\( \\mu_2 \\),..,\\( \\mu_a \\) (comma delimited) for \\(H_A\\):', "5, 8, 2, 6")
textInput(inputId = 'vec2', 'Enter \\( n_1 \\), \\( n_2 \\),..,\\( n_a \\) (comma delimited):', "25, 30, 20, 23")
numericInput(inputId = "Sigma", label = "Enter \\((\\sigma)\\):", value = 6, min = 0.001, max = 100000, step = 1)
sliderInput(inputId = "Alpha", label = "Significance level \\((\\alpha)\\)- red/purple shading in the null distribution:", min = 0.01, max = 0.25, value = 0.05, step = 0.01)
```



Column
-------

### 

```{r}
renderPlot({
    powerg(muvec = input$vec1,
           nvec = input$vec2,
           alpha = input$Alpha,
           sig = input$Sigma
           )
  })
```


